/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_prestasi_iovasi;

import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Compaq
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
        private DefaultTableModel table_karyawan_model;
       private DefaultTableModel table_prestasi_model;

    public main() {
        initComponents();
       // tampil_karyawan();
        id_prestasi.setEnabled(false);
        tampil_prestasi();
        URL image_path = getClass().getResource("/data_prestasi_iovasi/logo.png");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(image_path));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        logo_hiasan = new javax.swing.JLabel();
        tahun_prestasi = new javax.swing.JTextField();
        nik_personil = new javax.swing.JTextField();
        gugus = new javax.swing.JTextField();
        prestasi = new javax.swing.JTextField();
        nama_personil = new javax.swing.JTextField();
        departemen_personil = new javax.swing.JTextField();
        nama_event = new javax.swing.JTextField();
        insert2 = new javax.swing.JButton();
        delete_button1 = new javax.swing.JButton();
        sebagai_combox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestasi = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        id_prestasi = new javax.swing.JTextField();
        tingkat_prestasi = new javax.swing.JComboBox();
        lokasi_event = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Prestasi dan Inovasi PT Petrokimia Gresik");

        panel_utama.setBackground(new java.awt.Color(255, 255, 255));

        logo_hiasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data_prestasi_iovasi/logo - Copy.png"))); // NOI18N

        tahun_prestasi.setText("Tahun Prestasi");
        tahun_prestasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun_prestasiActionPerformed(evt);
            }
        });

        nik_personil.setText("NIK Personil");
        nik_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik_personilActionPerformed(evt);
            }
        });

        gugus.setText("Gugus");
        gugus.setToolTipText("");
        gugus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gugusActionPerformed(evt);
            }
        });

        prestasi.setText("Prestasi");
        prestasi.setToolTipText("");
        prestasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestasiActionPerformed(evt);
            }
        });

        nama_personil.setText("Nama Personil");
        nama_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_personilActionPerformed(evt);
            }
        });

        departemen_personil.setText("Departemen Personil");
        departemen_personil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departemen_personilActionPerformed(evt);
            }
        });

        nama_event.setText("Nama Event");
        nama_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_eventActionPerformed(evt);
            }
        });

        insert2.setText("Insert");
        insert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert2ActionPerformed(evt);
            }
        });

        delete_button1.setBackground(new java.awt.Color(255, 153, 153));
        delete_button1.setText("Delete");
        delete_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button1ActionPerformed(evt);
            }
        });

        sebagai_combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sebagai_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebagai_comboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Univers", 1, 14)); // NOI18N
        jLabel2.setText("Data Prestasi");

        table_prestasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_prestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_prestasiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_prestasi);

        refresh.setText("Refresh");
        refresh.setToolTipText("");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        cari.setText("Cari Nama/NIK");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jButton3.setText("Q");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(153, 153, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        id_prestasi.setText("ID Prestasi");
        id_prestasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_prestasiActionPerformed(evt);
            }
        });

        tingkat_prestasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tingkat_prestasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tingkat_prestasiActionPerformed(evt);
            }
        });

        lokasi_event.setText("Tingkat Prestasi");
        lokasi_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasi_eventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_utamaLayout = new javax.swing.GroupLayout(panel_utama);
        panel_utama.setLayout(panel_utamaLayout);
        panel_utamaLayout.setHorizontalGroup(
            panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_utamaLayout.createSequentialGroup()
                        .addComponent(logo_hiasan)
                        .addGap(18, 18, 18)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_utamaLayout.createSequentialGroup()
                                .addGap(0, 488, Short.MAX_VALUE)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(refresh))
                            .addGroup(panel_utamaLayout.createSequentialGroup()
                                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_utamaLayout.createSequentialGroup()
                                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(panel_utamaLayout.createSequentialGroup()
                                                .addComponent(sebagai_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_utamaLayout.createSequentialGroup()
                                                .addComponent(nama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahun_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(departemen_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama_event, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel_utamaLayout.createSequentialGroup()
                                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gugus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nik_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lokasi_event, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tingkat_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(panel_utamaLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(insert2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_utamaLayout.setVerticalGroup(
            panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo_hiasan)
                    .addGroup(panel_utamaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tahun_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nama_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nik_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gugus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lokasi_event, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departemen_personil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tingkat_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_event, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sebagai_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert2)
                            .addComponent(delete_button1)
                            .addComponent(edit))
                        .addGap(1, 1, 1)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(refresh))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tahun_prestasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun_prestasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun_prestasiActionPerformed

    private void nik_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik_personilActionPerformed

    private void gugusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gugusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gugusActionPerformed

    private void prestasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestasiActionPerformed

    private void nama_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_personilActionPerformed

    private void departemen_personilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departemen_personilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departemen_personilActionPerformed

    private void nama_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_eventActionPerformed

    private void sebagai_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebagai_comboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sebagai_comboxActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
       
        cari.setText("Cari Nama/NIK");
          nama_personil.setText("Nama Personil");
        nik_personil.setText("NIK Personil");
        departemen_personil.setText("Departemen Personil");
       gugus.setText("Gugus");
       prestasi.setText("Prestasi");
       nama_event.setText("Nama Event");
       tahun_prestasi.setText("Tahun Prestasi");
         sebagai_combox.setEditable(true);
                departemen_personil.setEditable(true); 
                           gugus.setEditable(true);
        nik_personil.setEditable(true);
        tahun_prestasi.setEditable(true);
        nama_event.setEditable(true);
        nama_personil.setEditable(true);
       // tampil_karyawan();
        tampil_prestasi();
         id_prestasi.setText("ID Prestasi");
         lokasi_event.setText("Tingkat Prestasi");
                 insert2.setEnabled(true);

    }//GEN-LAST:event_refreshActionPerformed

    public void refresh(){
               
        cari.setText("Cari Nama/NIK");
          nama_personil.setText("Nama Personil");
        nik_personil.setText("NIK Personil");
        departemen_personil.setText("Departemen Personil");
       gugus.setText("Gugus");
       prestasi.setText("Prestasi");
       nama_event.setText("Nama Event");
       tahun_prestasi.setText("Tahun Prestasi");
         sebagai_combox.setEditable(true);
                departemen_personil.setEditable(true); 
                           gugus.setEditable(true);
        nik_personil.setEditable(true);
        tahun_prestasi.setEditable(true);
        nama_event.setEditable(true);
        nama_personil.setEditable(true);
       // tampil_karyawan();
        id_prestasi.setText("ID Prestasi");
         lokasi_event.setText("Lokasi Event");
        tampil_prestasi();
        insert2.setEnabled(true);
    }
    
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cariActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           String nama_cari = cari.getText();
    //Driver
     Object[] Baris = {"NIK Karyawan","NIK SAP Karywan","Nama Karyawan","Departemen"};
           table_karyawan_model = new DefaultTableModel(null, Baris);

           //panggil method koneksi
           java.sql.Connection koneksi = new SQLHelper().connect();

           //untuk menampilkan di table
           try{
               String sql="Select * from karyawan where nama_karyawan like '%"+nama_cari+"%' or nik_karyawan='"+nama_cari+"'";
               java.sql.Statement stmt=koneksi.createStatement();
               java.sql.ResultSet rslt=stmt.executeQuery(sql);
               while(rslt.next()){
              //String id = rslt.getString("id_karyawan");
              String nik = rslt.getString("nik_karyawan");
              String nik_sap = rslt.getString("nik_sap_karyawan");
              String nama = rslt.getString("nama_karyawan");
              String departemen = rslt.getString("departemen_karyawan");
              String[] dataField={nik,nik_sap,nama,departemen};
              table_karyawan_model.addRow(dataField);
          }

          
        } catch (Exception e) {
        }
       

      
      
          String[] items = {"Ketua", "Anggota", "Sekertaris"};
        sebagai_combox.setModel(new javax.swing.DefaultComboBoxModel(items));
        //combo box
        Object[] Barist = {"Nama Event","Tahun Event","Prestasi","Gugus","NIK","Nama Personel","departemen","Sebagai"};     table_karyawan_model = new DefaultTableModel(null, Baris);
             table_prestasi_model = new DefaultTableModel(null, Barist);
        table_prestasi.setModel(table_prestasi_model);
     java.sql.Connection koneksit = new SQLHelper().connect();
        try {
          String sql="Select * from prestasi where nama_personil like '%"+nama_cari+"%' or nik_personil='"+nama_cari+"'";
          java.sql.Statement stmtt=koneksit.createStatement();
          java.sql.ResultSet rsltt=stmtt.executeQuery(sql);
          while(rsltt.next()){
              //String id = rslt.getString("id_karyawan");
              String nama = rsltt.getString("nama_event");
              System.out.println(nama);
              String tahun_event = rsltt.getString("tahun_event");
              String prestasi_event = rsltt.getString("prestasi_event");
              String gugus_event = rsltt.getString("gugus_event");
              String nik = rsltt.getString("nik_personil");
              String nama_personil = rsltt.getString("nama_personil");
              String departemen = rsltt.getString("departemen_personil");
              System.out.println(departemen);
              String sebagai = rsltt.getString("sebagai");
              String[] dataField={nama,tahun_event,prestasi_event,gugus_event,nik,nama_personil,departemen,sebagai};
              table_prestasi_model.addRow(dataField);
          }

          
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void insert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert2ActionPerformed
        // TODO add your handling code here:
              
        if( nik_personil.getText().equals("") ||  nik_personil.getText().equals("NIK Personil")){
                  JOptionPane.showMessageDialog(null,"Form Kosong Masukkan data dengan benar!","Peringatan",JOptionPane.WARNING_MESSAGE);
        }else{
              try{
            Connection koneksi = new SQLHelper().connect();
            String sql = "insert into prestasi(nama_event, tahun_event, prestasi_event, gugus_event,nama_personil,nik_personil,departemen_personil,sebagai,tingkat_event,lokasi_event)"
            + " values(?,?,?,?,?,?,?,?,?,?)";
            java.sql.PreparedStatement stmt = koneksi.prepareStatement(sql);
           
            try{
                stmt.setString(1,nama_event.getText());
                stmt.setString(2,tahun_prestasi.getText());
                stmt.setString(3,prestasi.getText());
                stmt.setString(4,gugus.getText());
                                stmt.setString(5,nama_personil.getText());
                stmt.setString(6,nik_personil.getText());
                stmt.setString(7,departemen_personil.getText());
                stmt.setString(8,sebagai_combox.getSelectedItem().toString());
              stmt.setString(9,tingkat_prestasi.getSelectedItem().toString());
                 stmt.setString(10,lokasi_event.getText());

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data berhasil disimpan!");
                //bersihkan teks
                //reset();
                refresh();
            }catch(SQLException se){
                //System.out.println("Gagal di simpan");
                JOptionPane.showMessageDialog(null,"Data Gagal disimpan!"
                    + "\nDengan Pesan : " + se.getMessage());
            }
            stmt.close();
        }catch(Exception e){}
        
        }
    }//GEN-LAST:event_insert2ActionPerformed

    private void table_prestasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prestasiMousePressed
        // TODO add your handling code here:
        int baris = table_prestasi.getSelectedRow();
        nama_personil.setText(table_prestasi.getValueAt(baris, 6).toString());
      //  nama_personil.setEditable(false);
        nama_event.setText(table_prestasi.getValueAt(baris, 1).toString());
        //nama_event.setEditable(false);
        tahun_prestasi.setText(table_prestasi.getValueAt(baris, 2).toString());
        //tahun_prestasi.setEditable(false);
        nik_personil.setText(table_prestasi.getValueAt(baris, 5).toString());
        //nik_personil.setEditable(false);
        gugus.setText(table_prestasi.getValueAt(baris,4 ).toString());
       // gugus.setEditable(false);
        departemen_personil.setText(table_prestasi.getValueAt(baris, 7).toString());
        //departemen_personil.setEditable(false); 
       // sebagai_combox.setText(table_prestasi.getValueAt(baris, 6).toString());
        //sebagai_combox.setEditable(false);
        insert2.setEnabled(false);
        prestasi.setText(table_prestasi.getValueAt(baris, 3).toString());
        String index = table_prestasi.getValueAt(baris,8).toString();
        System.out.println(index);
        sebagai_combox.setSelectedItem(table_prestasi.getValueAt(baris,8).toString());
        id_prestasi.setText(table_prestasi.getValueAt(baris,0).toString());
        lokasi_event.setText(table_prestasi.getValueAt(baris,2).toString());
    }//GEN-LAST:event_table_prestasiMousePressed

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
        // TODO add your handling code here:
          
        if( id_prestasi.getText().equals("") ||  id_prestasi.getText().equals("ID Prestasi")){
                  JOptionPane.showMessageDialog(null,"Tidak ada Data yang di hapus pilih data terebih dahulu","Peringatan",JOptionPane.WARNING_MESSAGE);
        }else{
          int dialogButton = JOptionPane.showConfirmDialog (null, "Apakah Anda yakin menghapus Prestasi "+prestasi.getText()+" ("+nama_personil.getText()+"-"+nik_personil.getText() +") ?","Tunggu Dulu Perhatikan!!!", JOptionPane.YES_NO_OPTION);
           if(dialogButton == JOptionPane.YES_OPTION) {
             try{
                //panggil method koneksi
                java.sql.Connection koneksi = new SQLHelper().connect();

                String sql="delete from prestasi where id_prestasi = '" 
                        + id_prestasi.getText()+"'";
                java.sql.PreparedStatement stmt=koneksi.prepareStatement(sql);
                stmt.executeUpdate();
                //bersihkan teks
                JOptionPane.showMessageDialog(null,"Data Berhasil dihapus");
                
               refresh();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal dihapus!"
                    + "\nDengan pesan error : " + e.getMessage());
            }
            System.out.println("yes_option");
        }
       if(dialogButton == JOptionPane.NO_OPTION) {
            /*try{
                
            }catch(Exception e){
                
            }*/
            System.out.println("no_option");
           

        }
        }
    }//GEN-LAST:event_delete_button1ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
      
    if(id_prestasi.getText().equals("")||id_prestasi.getText().equals("ID Prestasi")){
      JOptionPane.showMessageDialog(null,"Tidak ada Data yang di update","Peringatan",JOptionPane.WARNING_MESSAGE);
    }else{
        int dialogButton = JOptionPane.showConfirmDialog (null, "Apakah Anda yakin memperbarui ID Prestasi "+id_prestasi.getText()+" ?","Tunggu Dulu Perhatikan!!!", JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION) {
            java.sql.Connection koneksi = new SQLHelper().connect();

        String sql="update prestasi set nama_event = ?, tahun_event = ?, prestasi_event = ?, gugus_event = ?, nama_personil = ?, nik_personil = ?, departemen_personil = ?, sebagai = ?, tingkat_event = ?, lokasi_event = ? where id_prestasi = '" 
                + id_prestasi.getText()+"'";
        java.sql.PreparedStatement stmt = null;
        try {
            stmt = koneksi.prepareStatement(sql);
        } catch (SQLException ex) {}

        try{
           stmt.setString(1,nama_event.getText());
                stmt.setString(2,tahun_prestasi.getText());
                stmt.setString(3,prestasi.getText());
                stmt.setString(4,gugus.getText());
                                stmt.setString(5,nama_personil.getText());
                stmt.setString(6,nik_personil.getText());
                stmt.setString(7,departemen_personil.getText());
                stmt.setString(8,sebagai_combox.getSelectedItem().toString());
              stmt.setString(9,tingkat_prestasi.getSelectedItem().toString());
                 stmt.setString(10,lokasi_event.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah!");
            refresh();
           
        }catch(SQLException se){
            JOptionPane.showMessageDialog(null,"Data gagal diubah!"
                + "\nTerjadi error dengan pesan : " + se.getMessage());
        }
        }
        if(dialogButton == JOptionPane.NO_OPTION) {
        }
    }
    }//GEN-LAST:event_editActionPerformed

    private void id_prestasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_prestasiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_id_prestasiActionPerformed

    private void tingkat_prestasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tingkat_prestasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tingkat_prestasiActionPerformed

    private void lokasi_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasi_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasi_eventActionPerformed
    
    private void tampil_prestasi(){
        //combo box
        String[] items = {"Ketua", "Anggota", "Sekertaris","Fasilitator","Bendahara","Ko. Team","Peserta",""};
        sebagai_combox.setModel(new javax.swing.DefaultComboBoxModel(items));
        //combo box
        //
        String[] items2 = {"Perusahaan", "Nasional", "Internasional","Regional"};
        tingkat_prestasi.setModel(new javax.swing.DefaultComboBoxModel(items2));
        //
        
        Object[] Baris = {"ID","Nama Event","Tahun Event","Prestasi","Gugus","NIK","Nama Personel","departemen","Sebagai","Lokasi Event","Lokasi Event"};     table_karyawan_model = new DefaultTableModel(null, Baris);
             table_prestasi_model = new DefaultTableModel(null, Baris);
        table_prestasi.setModel(table_prestasi_model);
     java.sql.Connection koneksi = new SQLHelper().connect();
        try {
          String sql="Select * from prestasi";
          java.sql.Statement stmt=koneksi.createStatement();
          java.sql.ResultSet rslt=stmt.executeQuery(sql);
          while(rslt.next()){
              String id = rslt.getString("id_prestasi");
              String nama = rslt.getString("nama_event");
              System.out.println(nama);
              String tahun_event = rslt.getString("tahun_event");
              String prestasi_event = rslt.getString("prestasi_event");
              String gugus_event = rslt.getString("gugus_event");
              String nik = rslt.getString("nik_personil");
              String nama_personil = rslt.getString("nama_personil");
              String departemen = rslt.getString("departemen_personil");
              System.out.println(departemen);
              String lokasi = rslt.getString("lokasi_event");
              String tingkat = rslt.getString("tingkat_event");
              String sebagai = rslt.getString("sebagai");
              String[] dataField={id,nama,tahun_event,prestasi_event,gugus_event,nik,nama_personil,departemen,sebagai,lokasi,tingkat};
              table_prestasi_model.addRow(dataField);
          }

          
        } catch (Exception e) {
        }

    }
   
   
    
    public void sorted(String param, String type){
        if(type.equals("desc")){
               Object[] Baris = {"NIK Karyawan","NIK SAP Karywan","Nama Karyawan","Departemen"};
     table_karyawan_model = new DefaultTableModel(null, Baris);
    /* table_karyawan.setModel(table_karyawan_model);
              java.sql.Connection koneksi = new SQLHelper().connect();
        try {
          String sql="Select * from karyawan order by "+param+" desc";
          java.sql.Statement stmt=koneksi.createStatement();
          java.sql.ResultSet rslt=stmt.executeQuery(sql);
          while(rslt.next()){
              //String id = rslt.getString("id_karyawan");
              String nik = rslt.getString("nik_karyawan");
              String nik_sap = rslt.getString("nik_sap_karyawan");
              String nama = rslt.getString("nama_karyawan");
              String departemen = rslt.getString("departemen_karyawan");
              String[] dataField={nik,nik_sap,nama,departemen};
              table_karyawan_model.addRow(dataField);
          }

          
        } catch (Exception e) {
        }
       
        }else if(type.equals("asc")){
              java.sql.Connection koneksi = new SQLHelper().connect();
        try {
               Object[] Baris = {"NIK Karyawan","NIK SAP Karywan","Nama Karyawan","Departemen"};
     table_karyawan_model = new DefaultTableModel(null, Baris);
     table_karyawan.setModel(table_karyawan_model);
          String sql="Select * from karyawan order by "+param+" asc";
          java.sql.Statement stmt=koneksi.createStatement();
          java.sql.ResultSet rslt=stmt.executeQuery(sql);
          while(rslt.next()){
              //String id = rslt.getString("id_karyawan");
              String nik = rslt.getString("nik_karyawan");
              String nik_sap = rslt.getString("nik_sap_karyawan");
              String nama = rslt.getString("nama_karyawan");
              String departemen = rslt.getString("departemen_karyawan");
              String[] dataField={nik,nik_sap,nama,departemen};
              table_karyawan_model.addRow(dataField);
          }

          
        } catch (Exception e) {
        }*/
       
        }
      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                /*SQLHelper test = new SQLHelper();
                System.err.println(test.connect());*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JButton delete_button1;
    private javax.swing.JTextField departemen_personil;
    private javax.swing.JButton edit;
    private javax.swing.JTextField gugus;
    private javax.swing.JTextField id_prestasi;
    private javax.swing.JButton insert2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_hiasan;
    private javax.swing.JTextField lokasi_event;
    private javax.swing.JTextField nama_event;
    private javax.swing.JTextField nama_personil;
    private javax.swing.JTextField nik_personil;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JTextField prestasi;
    private javax.swing.JButton refresh;
    private javax.swing.JComboBox sebagai_combox;
    private javax.swing.JTable table_prestasi;
    private javax.swing.JTextField tahun_prestasi;
    private javax.swing.JComboBox tingkat_prestasi;
    // End of variables declaration//GEN-END:variables
}
